dependencies {
    implementation project(':model')
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'jakarta.persistence:jakarta.persistence-api' // TODO: Check if it's still necessary
    implementation 'io.asyncer:r2dbc-mysql:1.4.0'
    implementation 'io.r2dbc:r2dbc-pool'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-mysql'
    implementation 'com.mysql:mysql-connector-j:9.1.0'
    implementation 'org.reactivecommons.utils:object-mapper-api:0.1.0'

    testImplementation 'org.reactivecommons.utils:object-mapper:0.1.0'
}

