server:
  port: "${SERVER_PORT}"
spring:
  application:
    name: "ms_solicitudes_crediya"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: "jdbc:mysql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}?serverTimezone=America/Bogota&useSSL=false&allowPublicKeyRetrieval=true"
    user: "${adapters.r2dbc.username}"
    password: "${adapters.r2dbc.password}"
    locations: "classpath:db/migration"
    connect-retries: 3
    placeholders:
      db: "${adapters.r2dbc.database}"
adapters:
  r2dbc:
    host: "${MYSQL_HOST:localhost}"
    port: "${MYSQL_PORT:3307}"
    database: "${MYSQL_DATABASE}"
    username: "${MYSQL_USER}"
    password: "${MYSQL_ROOT_PASSWORD}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  restconsumer:
    timeout: 5000
    url: "${REST_CONSUMER_HOST:http://localhost:8001}"
  sqs:
    notifications:
      region: "${AWS_REGION}"
      queueUrl: "${AWS_SQS_QUEUEURL_NOTIFICATIONS}"
      endpoint: "${AWS_SQS_ENDPOINT}"
    capacity:
      region: "${AWS_REGION}"
      queueUrl: "${AWS_SQS_QUEUEURL_CAPACITY}"
      endpoint: "${AWS_SQS_ENDPOINT}"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
jwt:
  secret: "${JWT_SECRET}"
entrypoint:
  sqs:
    region: "${AWS_REGION}"
    endpoint: "${AWS_SQS_ENDPOINT}"
    queueUrl: "${AWS_SQS_QUEUEURL_STATE}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 30
    numberOfThreads: 1
